language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
before_install:
- chmod +x ./tools/install.sh
- chmod +x ./tools/build.sh
install:
- ./tools/install.sh
script:
- ./tools/build.sh
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file:
  - "./bin/Roll-a-ball-linux.zip"
  - "./bin/Roll-a-ball-windows.zip"
  skip_cleanup: true
  on:
    tags: true
