language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
env:
- project="Roll a Ball" target="Linux"   option="buildLinuxUniversalPlayer"
- project="Roll a Ball" target="Mac"     option="buildOSXUniversalPlayer"
- project="Roll a Ball" target="Windows" option="buildWindowsPlayer"
- project="Tanks!" target="Linux"   option="buildLinuxUniversalPlayer"
- project="Tanks!" target="Mac"     option="buildOSXUniversalPlayer"
- project="Tanks!" target="Windows" option="buildWindowsPlayer"
before_install:
- chmod +x ./tools/install.sh
- chmod +x ./tools/build.sh
install:
- ./tools/install.sh "$target"
script:
- ./tools/build.sh "$project" "$target" "$option"
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file:
  - "./bin/${project}-${target}.zip"
  skip_cleanup: true
  on:
    tags: true
