`unitytuts` is just a repository for me to learn about Unity.
Things learnt:

== Roll-a-Ball tutorial

* Only commit the bare minimum number of files for Unity to recognize a folder as a Unity project.
  Use https://www.gitignore.io[gitignore.io] to have an idea of what shouldn't be commited (YMMV).
  In particular:
** one should commit `.meta` files: this is recommended by Unity.
   https://blog.forrestthewoods.com/managing-meta-files-in-unity-713166ee3d30#.35zjl0w5m[Here] is an explanation. +
   TL;DR: scenes reference `.meta` files identifiers, so forgetting them breaks scenes.
** V$ `.sln` and `.csproj` files, as long as `Library`, `obj` and `Temp` folders are generated by Unity on build
   (https://unity3d.com/fr/learn/tutorials/topics/production/mastering-unity-project-folder-structure-version-control-systems[source]).
* Unity uses a lot of binary files.
  As many of these live and may change during development, and as git doesn't properly manage binaries in its diffs,
  precommit/prepull hooks should be used in conjunction with something like `git-annex` or `git-fat` as long as a separate repository
  (http://stackoverflow.com/questions/540535/managing-large-binary-files-with-git/29530784)[directions].
